version: 2

builds:
  - dir: .
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -X main.Version={{ .Tag }}
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
