name: Push commits
on:
  push:
    branches: [master]
    tags-ignore: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
